//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_aspnet_mvc_crud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<module> Module { get; set; }
        public virtual DbSet<module_category> ModuleCategory { get; set; }
        public virtual DbSet<note> Note { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<task> Task { get; set; }
        public virtual DbSet<task_note> TaskNote { get; set; }
        public virtual DbSet<user> User { get; set; }
        public virtual DbSet<user_action> UserAction { get; set; }
        public virtual DbSet<user_permission> UserPermission { get; set; }
        public virtual DbSet<user_position> UserPosition { get; set; }
    }
}
