//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_aspnet_mvc_crud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseEntities : DbContext
    {
        public DataBaseEntities()
            : base("name=DataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<module> module { get; set; }
        public virtual DbSet<module_category> module_category { get; set; }
        public virtual DbSet<note> note { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<task_note> task_note { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_action> user_action { get; set; }
        public virtual DbSet<user_permission> user_permission { get; set; }
        public virtual DbSet<user_position> user_position { get; set; }
    }
}
