//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_aspnet_mvc_crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_permission
    {
        public int id { get; set; }
        public int user_position_id { get; set; }
        public int user_action_id { get; set; }
    
        public virtual user_action user_action { get; set; }
        public virtual user_position user_position { get; set; }
    }
}
