//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cs_aspnet_mvc_crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_action
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_action()
        {
            this.user_permission = new HashSet<user_permission>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int module_id { get; set; }
    
        public virtual module module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_permission> user_permission { get; set; }
    }
}
